version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=sqlite:///./image_classifier.db
      - SECRET_KEY=supersecretkey
    volumes:
      - .:/app